/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProjectOtherSettings
 */
export interface ProjectOtherSettings {
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  labelNamesPath?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ProjectOtherSettings
   */
  splitFilePaths?: Array<string>;
}

export function ProjectOtherSettingsFromJSON(json: any): ProjectOtherSettings {
  return ProjectOtherSettingsFromJSONTyped(json, false);
}

export function ProjectOtherSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectOtherSettings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    labelNamesPath: !exists(json, 'label_names_path') ? undefined : json['label_names_path'],
    splitFilePaths: !exists(json, 'split_file_paths') ? undefined : json['split_file_paths'],
  };
}

export function ProjectOtherSettingsToJSON(value?: ProjectOtherSettings | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    label_names_path: value.labelNamesPath,
    split_file_paths: value.splitFilePaths,
  };
}
