/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProjectOtherSettings
 */
export interface ProjectOtherSettings {
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  mlBackendUrl?: string;
}

export function ProjectOtherSettingsFromJSON(json: any): ProjectOtherSettings {
  return ProjectOtherSettingsFromJSONTyped(json, false);
}

export function ProjectOtherSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectOtherSettings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    mlBackendUrl: !exists(json, 'mlBackendUrl') ? undefined : json['mlBackendUrl'],
  };
}

export function ProjectOtherSettingsToJSON(value?: ProjectOtherSettings | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    mlBackendUrl: value.mlBackendUrl,
  };
}
