/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  Points2polygonRequest,
  Points2polygonRequestFromJSON,
  Points2polygonRequestToJSON,
} from '../models';

export interface Points2polygonOperationRequest {
  points2polygonRequest?: Points2polygonRequest;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   *
   */
  async points2polygonRaw(
    requestParameters: Points2polygonOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/rpc/seg/points2polygon`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: Points2polygonRequestToJSON(requestParameters.points2polygonRequest),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   *
   */
  async points2polygon(
    points2polygonRequest?: Points2polygonRequest,
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<Array<string>> {
    const response = await this.points2polygonRaw(
      { points2polygonRequest: points2polygonRequest },
      initOverrides,
    );
    return await response.value();
  }
}
