/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { InlineObject6, InlineObject6FromJSON, InlineObject6ToJSON } from '../models';

export interface GetFoldersRequest {
  inlineObject6?: InlineObject6;
}

/**
 *
 */
export class RpcApi extends runtime.BaseAPI {
  /**
   */
  async getFoldersRaw(
    requestParameters: GetFoldersRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/rpc/folders`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: InlineObject6ToJSON(requestParameters.inlineObject6),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async getFolders(inlineObject6?: InlineObject6, initOverrides?: RequestInit): Promise<void> {
    await this.getFoldersRaw({ inlineObject6: inlineObject6 }, initOverrides);
  }
}
