/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { Tag, TagFromJSON, TagToJSON } from '../models';

export interface CreateRequest {
  tag: Tag;
  requestId?: string;
}

export interface GetRequest {
  tagId: string;
}

export interface RemoveRequest {
  tagId: string;
}

export interface UpdateRequest {
  tagId: string;
  tag: Tag;
}

/**
 *
 */
export class TagApi extends runtime.BaseAPI {
  /**
   * Create a new tag
   */
  async createRaw(
    requestParameters: CreateRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters.tag === null || requestParameters.tag === undefined) {
      throw new runtime.RequiredError(
        'tag',
        'Required parameter requestParameters.tag was null or undefined when calling create.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (requestParameters.requestId !== undefined && requestParameters.requestId !== null) {
      headerParameters['request_id'] = String(requestParameters.requestId);
    }

    const response = await this.request(
      {
        path: `/tags`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: TagToJSON(requestParameters.tag),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
  }

  /**
   * Create a new tag
   */
  async create(tag: Tag, requestId?: string, initOverrides?: RequestInit): Promise<Tag> {
    const response = await this.createRaw({ tag: tag, requestId: requestId }, initOverrides);
    return await response.value();
  }

  /**
   * Get info of a specific tag
   */
  async getRaw(
    requestParameters: GetRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters.tagId === null || requestParameters.tagId === undefined) {
      throw new runtime.RequiredError(
        'tagId',
        'Required parameter requestParameters.tagId was null or undefined when calling get.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tags/{tag_id}`.replace(
          `{${'tag_id'}}`,
          encodeURIComponent(String(requestParameters.tagId)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
  }

  /**
   * Get info of a specific tag
   */
  async get(tagId: string, initOverrides?: RequestInit): Promise<Tag> {
    const response = await this.getRaw({ tagId: tagId }, initOverrides);
    return await response.value();
  }

  /**
   * Get all tags, sort by last modify date
   */
  async getAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Tag>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tags`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TagFromJSON));
  }

  /**
   * Get all tags, sort by last modify date
   */
  async getAll(initOverrides?: RequestInit): Promise<Array<Tag>> {
    const response = await this.getAllRaw(initOverrides);
    return await response.value();
  }

  /**
   * Delete a tag and ALL TAGGING RECORDS under this tag.
   * Delete a tag and ALL TAGGING RECORDS under this tag.
   */
  async removeRaw(
    requestParameters: RemoveRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.tagId === null || requestParameters.tagId === undefined) {
      throw new runtime.RequiredError(
        'tagId',
        'Required parameter requestParameters.tagId was null or undefined when calling remove.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tags/{tag_id}`.replace(
          `{${'tag_id'}}`,
          encodeURIComponent(String(requestParameters.tagId)),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a tag and ALL TAGGING RECORDS under this tag.
   * Delete a tag and ALL TAGGING RECORDS under this tag.
   */
  async remove(tagId: string, initOverrides?: RequestInit): Promise<void> {
    await this.removeRaw({ tagId: tagId }, initOverrides);
  }

  /**
   * Edit tag properties. Empty strings will be set. Properties not in request body won\'t be changed
   * Edit tag properties
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<Tag>> {
    if (requestParameters.tagId === null || requestParameters.tagId === undefined) {
      throw new runtime.RequiredError(
        'tagId',
        'Required parameter requestParameters.tagId was null or undefined when calling update.',
      );
    }

    if (requestParameters.tag === null || requestParameters.tag === undefined) {
      throw new runtime.RequiredError(
        'tag',
        'Required parameter requestParameters.tag was null or undefined when calling update.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/tags/{tag_id}`.replace(
          `{${'tag_id'}}`,
          encodeURIComponent(String(requestParameters.tagId)),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: TagToJSON(requestParameters.tag),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TagFromJSON(jsonValue));
  }

  /**
   * Edit tag properties. Empty strings will be set. Properties not in request body won\'t be changed
   * Edit tag properties
   */
  async update(tagId: string, tag: Tag, initOverrides?: RequestInit): Promise<Tag> {
    const response = await this.updateRaw({ tagId: tagId, tag: tag }, initOverrides);
    return await response.value();
  }
}
