/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { Task, TaskFromJSON, TaskToJSON } from '../models';

export interface GetRequest {
  taskId: string;
}

export interface RemoveRequest {
  taskId: string;
}

export interface UpdateRequest {
  taskId: string;
  task: Task;
}

/**
 *
 */
export class TaskApi extends runtime.BaseAPI {
  /**
   * Create a new task
   */
  async createRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Task>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tasks`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
  }

  /**
   * Create a new task
   */
  async create(initOverrides?: RequestInit): Promise<Task> {
    const response = await this.createRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get info of a specific task
   */
  async getRaw(
    requestParameters: GetRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<Task>> {
    if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
      throw new runtime.RequiredError(
        'taskId',
        'Required parameter requestParameters.taskId was null or undefined when calling get.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tasks/{task_id}`.replace(
          `{${'task_id'}}`,
          encodeURIComponent(String(requestParameters.taskId)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
  }

  /**
   * Get info of a specific task
   */
  async get(taskId: string, initOverrides?: RequestInit): Promise<Task> {
    const response = await this.getRaw({ taskId: taskId }, initOverrides);
    return await response.value();
  }

  /**
   * Your GET endpoint
   */
  async getAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Task>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tasks`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
  }

  /**
   * Your GET endpoint
   */
  async getAll(initOverrides?: RequestInit): Promise<Array<Task>> {
    const response = await this.getAllRaw(initOverrides);
    return await response.value();
  }

  /**
   * Delete a task and ALL DATA and ANNOTATIONS under the project. Won\'t delete file on file system
   * Delete a task and ALL DATA and ANNOTATIONS under the task.
   */
  async removeRaw(
    requestParameters: RemoveRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
      throw new runtime.RequiredError(
        'taskId',
        'Required parameter requestParameters.taskId was null or undefined when calling remove.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/tasks/{task_id}`.replace(
          `{${'task_id'}}`,
          encodeURIComponent(String(requestParameters.taskId)),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a task and ALL DATA and ANNOTATIONS under the project. Won\'t delete file on file system
   * Delete a task and ALL DATA and ANNOTATIONS under the task.
   */
  async remove(taskId: string, initOverrides?: RequestInit): Promise<void> {
    await this.removeRaw({ taskId: taskId }, initOverrides);
  }

  /**
   * Edit task info. Provide key value pair to change one value only. Provide all changed values to change multiple. Empty string will be set. Leave values don\'t intend to change out of request body.
   * Edit task info
   */
  async updateRaw(
    requestParameters: UpdateRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<Task>> {
    if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
      throw new runtime.RequiredError(
        'taskId',
        'Required parameter requestParameters.taskId was null or undefined when calling update.',
      );
    }

    if (requestParameters.task === null || requestParameters.task === undefined) {
      throw new runtime.RequiredError(
        'task',
        'Required parameter requestParameters.task was null or undefined when calling update.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/tasks/{task_id}`.replace(
          `{${'task_id'}}`,
          encodeURIComponent(String(requestParameters.taskId)),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: TaskToJSON(requestParameters.task),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
  }

  /**
   * Edit task info. Provide key value pair to change one value only. Provide all changed values to change multiple. Empty string will be set. Leave values don\'t intend to change out of request body.
   * Edit task info
   */
  async update(taskId: string, task: Task, initOverrides?: RequestInit): Promise<Task> {
    const response = await this.updateRaw({ taskId: taskId, task: task }, initOverrides);
    return await response.value();
  }
}
