/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoadRequest,
  Model,
  PredictRequest,
  TrainRequest,
} from '../models';
import {
    LoadRequestFromJSON,
    LoadRequestToJSON,
    ModelFromJSON,
    ModelToJSON,
    PredictRequestFromJSON,
    PredictRequestToJSON,
    TrainRequestFromJSON,
    TrainRequestToJSON,
} from '../models';

export interface EvaluateRequest {
    modelName: string;
}

export interface GetProgressRequest {
    modelName: string;
}

export interface LoadOperationRequest {
    modelName: string;
    loadRequest?: LoadRequest;
}

export interface PredictOperationRequest {
    modelName: string;
    predictRequest?: PredictRequest;
}

export interface TrainOperationRequest {
    modelName: string;
    trainRequest?: TrainRequest;
}

export interface UnloadRequest {
    modelName: string;
}

/**
 * 
 */
export class ModelApi extends runtime.BaseAPI {

    /**
     * Evaluate model performance
     * Evaluate model performance
     */
    async evaluateRaw(requestParameters: EvaluateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling evaluate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{model_name}/eval`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Evaluate model performance
     * Evaluate model performance
     */
    async evaluate(modelName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.evaluateRaw({ modelName: modelName }, initOverrides);
    }

    /**
     * Get all models
     * Get all models
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Model>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelFromJSON));
    }

    /**
     * Get all models
     * Get all models
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Model>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get training progress
     * Get training progress
     */
    async getProgressRaw(requestParameters: GetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling getProgress.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{model_name}/train`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get training progress
     * Get training progress
     */
    async getProgress(modelName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getProgressRaw({ modelName: modelName }, initOverrides);
    }

    /**
     * Detect ml backend running
     * Detect ml backend running
     */
    async isBackendUpRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/running`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Detect ml backend running
     * Detect ml backend running
     */
    async isBackendUp(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isBackendUpRaw(initOverrides);
        return await response.value();
    }

    /**
     * Load model
     * Load a model into memory. Model must be loaded before being used.
     */
    async loadRaw(requestParameters: LoadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling load.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/{model_name}/load`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoadRequestToJSON(requestParameters.loadRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Load model
     * Load a model into memory. Model must be loaded before being used.
     */
    async load(modelName: string, loadRequest?: LoadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loadRaw({ modelName: modelName, loadRequest: loadRequest }, initOverrides);
    }

    /**
     * Predict
     * Predict
     */
    async predictRaw(requestParameters: PredictOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling predict.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/{model_name}/predict`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PredictRequestToJSON(requestParameters.predictRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Predict
     * Predict
     */
    async predict(modelName: string, predictRequest?: PredictRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.predictRaw({ modelName: modelName, predictRequest: predictRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Train a model
     * Train a model
     */
    async trainRaw(requestParameters: TrainOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling train.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/{model_name}/train`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainRequestToJSON(requestParameters.trainRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Train a model
     * Train a model
     */
    async train(modelName: string, trainRequest?: TrainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainRaw({ modelName: modelName, trainRequest: trainRequest }, initOverrides);
    }

    /**
     * Unload model
     * Unload a model to free up memory
     */
    async unloadRaw(requestParameters: UnloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling unload.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{model_name}/unload`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unload model
     * Unload a model to free up memory
     */
    async unload(modelName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unloadRaw({ modelName: modelName }, initOverrides);
    }

}
