/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
  /**
   *
   * @type {object}
   * @memberof InlineObject2
   */
  initParams?: object;
}

export function InlineObject2FromJSON(json: any): InlineObject2 {
  return InlineObject2FromJSONTyped(json, false);
}

export function InlineObject2FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject2 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    initParams: !exists(json, 'init_params') ? undefined : json['init_params'],
  };
}

export function InlineObject2ToJSON(value?: InlineObject2 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    init_params: value.initParams,
  };
}
