/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  img: string;
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  format: string;
  /**
   *
   * @type {boolean}
   * @memberof InlineObject1
   */
  createLabel?: boolean;
}

export function InlineObject1FromJSON(json: any): InlineObject1 {
  return InlineObject1FromJSONTyped(json, false);
}

export function InlineObject1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject1 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    img: json['img'],
    format: json['format'],
    createLabel: !exists(json, 'create_label') ? undefined : json['create_label'],
  };
}

export function InlineObject1ToJSON(value?: InlineObject1 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    img: value.img,
    format: value.format,
    create_label: value.createLabel,
  };
}
