/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Model
 */
export interface Model {
  /**
   *
   * @type {string}
   * @memberof Model
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Model
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof Model
   */
  taskCategory?: string;
  /**
   *
   * @type {string}
   * @memberof Model
   */
  framework?: string;
}

export function ModelFromJSON(json: any): Model {
  return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    taskCategory: !exists(json, 'task_category') ? undefined : json['task_category'],
    framework: !exists(json, 'framework') ? undefined : json['framework'],
  };
}

export function ModelToJSON(value?: Model | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    task_category: value.taskCategory,
    framework: value.framework,
  };
}
