/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelNamePredictOther
 */
export interface ModelNamePredictOther {
  /**
   *
   * @type {Array<any>}
   * @memberof ModelNamePredictOther
   */
  clicks?: Array<any>;
}

export function ModelNamePredictOtherFromJSON(json: any): ModelNamePredictOther {
  return ModelNamePredictOtherFromJSONTyped(json, false);
}

export function ModelNamePredictOtherFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelNamePredictOther {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    clicks: !exists(json, 'clicks') ? undefined : json['clicks'],
  };
}

export function ModelNamePredictOtherToJSON(value?: ModelNamePredictOther | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    clicks: value.clicks,
  };
}
