/* tslint:disable */
/* eslint-disable */
/**
 * PP Label ML backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictRequestOther
 */
export interface PredictRequestOther {
    /**
     * 
     * @type {Array<any>}
     * @memberof PredictRequestOther
     */
    clicks?: Array<any>;
}

/**
 * Check if a given object implements the PredictRequestOther interface.
 */
export function instanceOfPredictRequestOther(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PredictRequestOtherFromJSON(json: any): PredictRequestOther {
    return PredictRequestOtherFromJSONTyped(json, false);
}

export function PredictRequestOtherFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictRequestOther {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clicks': !exists(json, 'clicks') ? undefined : json['clicks'],
    };
}

export function PredictRequestOtherToJSON(value?: PredictRequestOther | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clicks': value.clicks,
    };
}

