/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateCacheRequest
 */
export interface CreateCacheRequest {
  /**
   *
   * @type {string}
   * @memberof CreateCacheRequest
   */
  content?: string;
}

/**
 * Check if a given object implements the CreateCacheRequest interface.
 */
export function instanceOfCreateCacheRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CreateCacheRequestFromJSON(json: any): CreateCacheRequest {
  return CreateCacheRequestFromJSONTyped(json, false);
}

export function CreateCacheRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCacheRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    content: !exists(json, 'content') ? undefined : json['content'],
  };
}

export function CreateCacheRequestToJSON(value?: CreateCacheRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    content: value.content,
  };
}
