/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Array<Label>,
    instanceOfArray<Label>,
    Array<Label>FromJSON,
    Array<Label>FromJSONTyped,
    Array<Label>ToJSON,
} from './Array&lt;Label&gt;';
import {
    Label,
    instanceOfLabel,
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
} from './Label';

/**
 * @type CreateRequest
 * 
 * @export
 */
export type CreateRequest = Array<Label> | Label;

export function CreateRequestFromJSON(json: any): CreateRequest {
    return CreateRequestFromJSONTyped(json, false);
}

export function CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Array<Label>FromJSONTyped(json, true), ...LabelFromJSONTyped(json, true) };
}

export function CreateRequestToJSON(value?: CreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfArray<Label>(value)) {
        return Array<Label>ToJSON(value as Array<Label>);
    }
    if (instanceOfLabel(value)) {
        return LabelToJSON(value as Label);
    }

    return {};
}

