/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Task } from './Task';
import { TaskFromJSON, TaskFromJSONTyped, TaskToJSON } from './Task';

/**
 *
 * @export
 * @interface Data
 */
export interface Data {
  /**
   *
   * @type {number}
   * @memberof Data
   */
  readonly dataId?: number;
  /**
   *
   * @type {number}
   * @memberof Data
   */
  taskId?: number;
  /**
   *
   * @type {string}
   * @memberof Data
   */
  size?: string;
  /**
   *
   * @type {Task}
   * @memberof Data
   */
  task?: Task;
  /**
   *
   * @type {string}
   * @memberof Data
   */
  readonly created?: string;
  /**
   *
   * @type {string}
   * @memberof Data
   */
  readonly modified?: string;
  /**
   *
   * @type {string}
   * @memberof Data
   */
  sault?: string;
  /**
   *
   * @type {boolean}
   * @memberof Data
   */
  predicted?: boolean;
}

/**
 * Check if a given object implements the Data interface.
 */
export function instanceOfData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function DataFromJSON(json: any): Data {
  return DataFromJSONTyped(json, false);
}

export function DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Data {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataId: !exists(json, 'data_id') ? undefined : json['data_id'],
    taskId: !exists(json, 'task_id') ? undefined : json['task_id'],
    size: !exists(json, 'size') ? undefined : json['size'],
    task: !exists(json, 'task') ? undefined : TaskFromJSON(json['task']),
    created: !exists(json, 'created') ? undefined : json['created'],
    modified: !exists(json, 'modified') ? undefined : json['modified'],
    sault: !exists(json, 'sault') ? undefined : json['sault'],
    predicted: !exists(json, 'predicted') ? undefined : json['predicted'],
  };
}

export function DataToJSON(value?: Data | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    task_id: value.taskId,
    size: value.size,
    task: TaskToJSON(value.task),
    sault: value.sault,
    predicted: value.predicted,
  };
}
