/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Web backend APIs for PaddleLabel
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExportDatasetRequest
 */
export interface ExportDatasetRequest {
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  exportDir: string;
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  exportFormat?: string;
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  segMaskType?: string;
}

/**
 * Check if a given object implements the ExportDatasetRequest interface.
 */
export function instanceOfExportDatasetRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'exportDir' in value;

  return isInstance;
}

export function ExportDatasetRequestFromJSON(json: any): ExportDatasetRequest {
  return ExportDatasetRequestFromJSONTyped(json, false);
}

export function ExportDatasetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExportDatasetRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    exportDir: json['export_dir'],
    exportFormat: !exists(json, 'export_format') ? undefined : json['export_format'],
    segMaskType: !exists(json, 'seg_mask_type') ? undefined : json['seg_mask_type'],
  };
}

export function ExportDatasetRequestToJSON(value?: ExportDatasetRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    export_dir: value.exportDir,
    export_format: value.exportFormat,
    seg_mask_type: value.segMaskType,
  };
}
