/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExportDatasetRequest
 */
export interface ExportDatasetRequest {
  /**
   *
   * @type {string}
   * @memberof ExportDatasetRequest
   */
  exportDir?: string;
}

export function ExportDatasetRequestFromJSON(json: any): ExportDatasetRequest {
  return ExportDatasetRequestFromJSONTyped(json, false);
}

export function ExportDatasetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExportDatasetRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    exportDir: !exists(json, 'export_dir') ? undefined : json['export_dir'],
  };
}

export function ExportDatasetRequestToJSON(value?: ExportDatasetRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    export_dir: value.exportDir,
  };
}
