/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetFoldersRequest
 */
export interface GetFoldersRequest {
  /**
   *
   * @type {string}
   * @memberof GetFoldersRequest
   */
  path?: string;
}

/**
 * Check if a given object implements the GetFoldersRequest interface.
 */
export function instanceOfGetFoldersRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetFoldersRequestFromJSON(json: any): GetFoldersRequest {
  return GetFoldersRequestFromJSONTyped(json, false);
}

export function GetFoldersRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetFoldersRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    path: !exists(json, 'path') ? undefined : json['path'],
  };
}

export function GetFoldersRequestToJSON(value?: GetFoldersRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    path: value.path,
  };
}
