/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse2002
   */
  projectId?: number;
}

export function InlineResponse2002FromJSON(json: any): InlineResponse2002 {
  return InlineResponse2002FromJSONTyped(json, false);
}

export function InlineResponse2002FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InlineResponse2002 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    projectId: !exists(json, 'project_id') ? undefined : json['project_id'],
  };
}

export function InlineResponse2002ToJSON(value?: InlineResponse2002 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    project_id: value.projectId,
  };
}
