/* tslint:disable */
/* eslint-disable */
/**
 * PP-Label API Spec
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PplabelApiControllerUserLoginRequest
 */
export interface PplabelApiControllerUserLoginRequest {
  /**
   *
   * @type {string}
   * @memberof PplabelApiControllerUserLoginRequest
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof PplabelApiControllerUserLoginRequest
   */
  password: string;
}

export function PplabelApiControllerUserLoginRequestFromJSON(
  json: any,
): PplabelApiControllerUserLoginRequest {
  return PplabelApiControllerUserLoginRequestFromJSONTyped(json, false);
}

export function PplabelApiControllerUserLoginRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PplabelApiControllerUserLoginRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
    password: json['password'],
  };
}

export function PplabelApiControllerUserLoginRequestToJSON(
  value?: PplabelApiControllerUserLoginRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    password: value.password,
  };
}
