/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProjectOtherSettings
 */
export interface ProjectOtherSettings {
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  mlBackendUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  perviousModel?: string;
  /**
   *
   * @type {object}
   * @memberof ProjectOtherSettings
   */
  models?: object;
  /**
   *
   * @type {string}
   * @memberof ProjectOtherSettings
   */
  segMaskType?: string;
}

/**
 * Check if a given object implements the ProjectOtherSettings interface.
 */
export function instanceOfProjectOtherSettings(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ProjectOtherSettingsFromJSON(json: any): ProjectOtherSettings {
  return ProjectOtherSettingsFromJSONTyped(json, false);
}

export function ProjectOtherSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectOtherSettings {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    mlBackendUrl: !exists(json, 'mlBackendUrl') ? undefined : json['mlBackendUrl'],
    perviousModel: !exists(json, 'perviousModel') ? undefined : json['perviousModel'],
    models: !exists(json, 'models') ? undefined : json['models'],
    segMaskType: !exists(json, 'segMaskType') ? undefined : json['segMaskType'],
  };
}

export function ProjectOtherSettingsToJSON(value?: ProjectOtherSettings | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    mlBackendUrl: value.mlBackendUrl,
    perviousModel: value.perviousModel,
    models: value.models,
    segMaskType: value.segMaskType,
  };
}
