/* tslint:disable */
/* eslint-disable */
/**
 * PaddleLabel API Specs
 * Back end APIs for PP-Label
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: me@linhan.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ToEasydataRequest
 */
export interface ToEasydataRequest {
  /**
   *
   * @type {string}
   * @memberof ToEasydataRequest
   */
  accessToken: string;
  /**
   *
   * @type {number}
   * @memberof ToEasydataRequest
   */
  datasetId: number;
}

/**
 * Check if a given object implements the ToEasydataRequest interface.
 */
export function instanceOfToEasydataRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'accessToken' in value;
  isInstance = isInstance && 'datasetId' in value;

  return isInstance;
}

export function ToEasydataRequestFromJSON(json: any): ToEasydataRequest {
  return ToEasydataRequestFromJSONTyped(json, false);
}

export function ToEasydataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ToEasydataRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accessToken: json['access_token'],
    datasetId: json['dataset_id'],
  };
}

export function ToEasydataRequestToJSON(value?: ToEasydataRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    access_token: value.accessToken,
    dataset_id: value.datasetId,
  };
}
